services:
    web:
        image: openresty/openresty:buster-fat
        ports: 
            - 5000:80
        volumes:
            - ./src:/etc/nginx/battlesnake
            - ./resty.conf:/etc/nginx/conf.d/default.conf